### ISSUE TITLE
Unable to assign BGP models to custom fields

### ISSUE THREAD

**Issue by mraerino** [netbox-community/netbox-bgp#212] opened 2024-09-29 19:31 UTC
**NetBox version**

4.0.9 with BGP plugin 0.13.2

**Describe the bug**

When creating a new custom field via the Netbox UI it's not possible to select any of the BGP models for assignment.

**To Reproduce**
1. Go to `/extras/custom-fields/add/` on your Netbox install
2. Try selecting a BGP plugin model from the `Object types` dropdown
3. See that none of the BGP models can be selected

**Expected behavior**

I expect to be able to assign custom fields to some of the BGP models, mostly sessions where the custom fields are documented in the API.

**Screenshots**

n/a

**Additional context**

n/a

**Comment by pl0xym0r** [comment] 2024-09-30 04:53
I'm not able to reproduce your issue, would you mind to share further information ?
![image](https://github.com/user-attachments/assets/5a6d203f-5e82-4a37-9c90-aded6e9553c6)
![image](https://github.com/user-attachments/assets/ea4cbe59-289b-4d45-b76d-6587d75d8ecb)

**Comment by cruse1977** [comment] 2024-10-07 16:15
I'm also not able to replicate this. I'm removing the label bug for now pending further information.

**Comment by rvtipper** [comment] 2024-11-13 12:11
I have this problem too but it is inconsistent as @mraerino mentions. 

Netbox:	4.0.11
Netbox BGP:	0.13.3

In my local instance running these versions (and with prod database imported) I don't experience this at all and can make custom fields on the BGP plugin without any problem. However in our production and test environments I experience this problem as described - the BGP plugin objects are not searchable. For a workaround I could create the custom field using API without any issue.

**Comment by cruse1977** [comment] 2024-11-19 21:08
I've set this to pending close  (as is the primary issue) as there's no easy way to replicate it - it would literally need a copy of databases to see why this occurs - its something database related.

**Comment by rvtipper** [comment] 2024-11-27 17:33
@cruse1977 ah interesting, the order I give the plugins matters for me. I am also running with the netbox secrets plugins (2.0.3), if that config line reads PLUGINS = ["netbox_bgp", "netbox_secrets"] then I can see BGP objects ok for tags and custom fields, if netbox secrets is given first then I can't. In both instances I can see netbox secrets objects ok.

**Comment by cruse1977** [comment] 2024-11-29 01:12
So the other case I'm aware of - also had netbox-secrets as the penultimate plugin prior to the one with model issues, so thats two cases.

**Comment by cruse1977** [comment] 2024-12-20 20:38
Closing this issue out - its not an issue with BGP, more likely secrets.

**Closed by cruse1977** 2024-12-20 20:38 UTC
Labels: revisions-needed, pending-closure

**Comment by Kani999** [comment] 2025-02-24 09:26
Could be related to https://github.com/netbox-community/netbox/discussions/17836
